### PR TITLE
Specify right dependencies versions in README

### PR DESCRIPTION
**Pull request by liubko**

### CODE REVIEW

**Comment by playpauseandstop** [comment]
Looks like you need another bump here :)

**Comment by playpauseandstop** [comment]
LGTM for future update

**Comment by liubko** [comment]
```
    "babel-eslint": "6.0.4",
    "eslint": "2.9.0",
    "eslint-plugin-react": "5.1.1"
```

versions in `readme` same as in `package.json`

**Comment by liubko** [comment]
@playpauseandstop ^

**Comment by liubko** [comment]
@playpauseandstop ^

**Comment by liubko** [comment]
fixed in https://github.com/ezhome/eslint-config-ezhome/pull/5

**Pull request closed without merging**
